version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    assignees:
      - 'wimpyprogrammer'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    assignees:
      - 'wimpyprogrammer'
    versioning-strategy: 'widen'
